Entity\EUserOauthAccount:
    type: entity
    table: e_user_oauth_account
    options:
        charset: utf8
        collate: utf8_general_ci
        comment: 用户开放平台账号表
    indexes:
        idx_userId:
            columns:
                - userId
        idx_platform:
            columns:
                - platform
        idx_application:
            columns:
                - application
        idx_expiredAt:
            columns:
                - expiredAt
    uniqueConstraints:
        uniq_ouid:
            columns:
                - openId
                - unionId
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: userId
        platform:
            type: string
            nullable: false
            length: 32
            options:
                comment: 类型:wechat|weibo|qq|douban|facebook|github|google|linkedin
        application:
            type: string
            nullable: false
            length: 32
            options:
                comment: 类型:wordscon-web|wordscon-official-accounts
        openId:
            type: string
            nullable: false
            length: 128
            options:
                comment: 同一用户在不同应用下登录openid不一样
            column: openId
        unionId:
            type: string
            nullable: true
            length: 128
            options:
                comment: 同一用户在不同应用下登录unionid一样
            column: unionId
        accessToken:
            type: string
            nullable: true
            length: 128
            options:
                comment: token
            column: accessToken
        refreshToken:
            type: string
            nullable: true
            length: 128
            options:
                comment: token
            column: refreshToken
        scope:
            type: string
            nullable: true
            length: 128
            options:
                comment: scope
        createdAt:
            type: datetime
            nullable: false
            column: createdAt
        expiredAt:
            type: datetime
            nullable: true
            options:
                comment: 失效时间
            column: expiredAt
        userInfo:
            type: text
            nullable: true
            column: userInfo
        sessionKey:
            type: string
            nullable: true
            column: sessionKey
